### ISSUE TITLE
TwentyTwenty-block: Parse Error

### ISSUE THREAD

**Issue by bph** [WordPress/theme-experiments#10]
Parse error: syntax error, unexpected ')' in /.../wp-content/themes/twentytwenty-blocks/functions.php on line 219

I uploaded the zipped directory to a clean WordPress install with Gutenberg 7.3 also tried it with Gutenberg 7.2, same error message on activation. 

PHP version is 7.2.9
Webserver: nginex 
WP 5.3.2

**Comment by jffng** [comment]
Thanks for testing this out @bph! 😃 

This looks to be a php version incompatibility. Anything below php 7.3 will throw this error.

I will look into php backwards compatibility and keep this issue up-to-date. What is strange to me is that we pulled these functions directly from the theme starter content of the official Twenty Twenty and Twenty Nineteen, and I would assume those had been tested against the versions of php that core supports.  

cc @kjellr

**Comment by bph** [comment]
You are welcome.  
I can confirm 
- the same error for TwentyNineteen-blocks (functions.php line 105) 
- upgrading my local dev environment to 7.3.2 the error message went away.

**Comment by kjellr** [comment]
Interesting! Thank you for testing, @bph. We'll sort this out.

**Comment by kjellr** [comment]
Fixed as of #13. 👍 Thanks again for the report.
