### ISSUE TITLE
Verse Block: Migrate styles to theme.json

### ISSUE THREAD

**Issue by scruffian** [WordPress/theme-experiments#100]
The editor styles are:

```
pre.wp-block-verse {
	padding: 0;
	color: currentColor;
}
```

The frontend styles are:
```
.wp-block-verse {
	font-family: var(--entry-content--font-family);
}
```

The font family will be handled by this PR: https://github.com/WordPress/gutenberg/pull/27332
The padding is being set by the block. I think we should move this to Global Styles, but its tricky because we need to set a default. I added this PR to track it: https://github.com/WordPress/gutenberg/issues/27338
The color seems unnecessary

**Comment by scruffian** [comment]
These issues are now closed.

**Comment by scruffian** [comment]
Reopening this, there were some issues with the implementation

**Comment by ooker777** [comment]
hi, any update on this? Why does the class has no formatting anymore?

**Comment by carolinan** [comment]
@ooker777 I don't believe TT1 Blocks had styles for verse block. Are you thinking of Twenty Twenty-One? Twenty Twenty-One is not supported in this GitHub repository.

**Comment by carolinan** [comment]
I don't believe there is anything left to fix here? If there is, then the issue can be reopened.

**Comment by ooker777** [comment]
Yes, I'm thinking about Twenty Twenty-One. I'm sorry for posting in the wrong repository. It's just in the top of Google
