### ISSUE TITLE
TT1 Blocks: Spacer Block: Migrate CSS to theme.json

### ISSUE THREAD

**Issue by scruffian** [WordPress/theme-experiments#130]
The code is [here](https://github.com/WordPress/twentytwentyone/tree/trunk/assets/sass/05-blocks/spacer).

From #82

**Comment by pbking** [comment]
According to [comments here](https://github.com/WordPress/theme-experiments/pull/109) I believe that the "mobile media query" style that TT1 blocks implemented will not be replicated for TT1-blocks.

The rest of the styles appear to already be reflected appropriately according to [this demonstration](https://2021blocks.wordpress.net/basic-block-patterns/).

I believe that this can simply be closed as the spacer works as expected without modification to either the theme or Gutenberg.

**Comment by kjellr** [comment]
Agreed, this one is all set. 👍
