### ISSUE TITLE
Rename Twenty Twenty-One Blocks and prepare it for inclusion in the theme directory

### ISSUE THREAD

**Issue by carolinan** [WordPress/theme-experiments#140]
It has been brought up that it may be easier for people to test and contribute to full site editing if Twenty Twenty-One blocks 
was available in the WordPress theme directory.

But if we add a second theme called Twenty Twenty-One to the directory, there is a real risk that users
downloads the wrong theme.
To avoid confusion about the differences between Twenty Twenty-One and Twenty Twenty-One Blocks, the full site editing
theme needs to be renamed.

One option would be to use the short version of the name that we as developers have been using: **TT1**, or **TT1 Blocks**.
A screenshot to further differentiate the themes would also be needed.

There are no technical difficulties with adding the theme to the directory, as long as a person with access to the https://wordpress.org/themes/author/wordpressdotorg/ account is available to do the theme uploads.

**Comment by jffng** [comment]
> One option would be to use the short version of the name that we as developers have been using: TT1, or TT1 Blocks.

I like TT1. It's simpler, like the block-based version of the theme.

> There are no technical difficulties with adding the theme to the directory, as long as a person with access to the https://wordpress.org/themes/author/wordpressdotorg/ account is available to do the theme uploads.

We can get started with that process of uploading a blank theme 🚀

**Comment by kjellr** [comment]
Confused people coming across this in search is definitely a concern, and a name change might help with that. 

Let's chat about this in [tomorrow's Block-based Themes meeting](https://make.wordpress.org/themes/2020/12/15/block-based-themes-meeting-agenda-december-16/). 👍

**Comment by carlomanf** [comment]
I'm just surprised no one brought up that there might be confusion between the extremely similar "Twenty Twenty-One" and "Twenty Twenty" but I guess it's too late for that.

**Comment by carolinan** [comment]
> I'm just surprised no one brought up that there might be confusion between the extremely similar "Twenty Twenty-One" and "Twenty Twenty" but I guess it's too late for that.

The default theme names are set, they are all part of a series and they are easy to recognize because of this.

The squad did briefly discuss using a different name also because Twenty Twenty-One _-and upcoming theme names-_ are very long. But it was never brought up with Matt.

**Comment by carolinan** [comment]
- [ ] Update screenshot
- [ ] Update the remaning `@subpackage`
- [ ] Add file header to functions.php

Before release:
Add templates for 

- [ ] search
- [ ]  archive

**Comment by kjellr** [comment]
Since the search and archive pages are noted in a separate issue now (#152), I'm going to mark this as resolved. Thanks!
