### ISSUE TITLE
TT1 Block: Button block styles missing

### ISSUE THREAD

**Issue by annezazu** [WordPress/theme-experiments#147]
Testing with Gutenberg 9.6 RC using WordPress 5.6 and found this button block issue: https://cloudup.com/cEMNxvpMOMH
It also happens with the Q theme so it's unclear to me how much of this is theme specific vs Gutenberg. If I need to report to the Gutenberg repo, let me know! Happy to do so but wanted to start here.

**Comment by kjellr** [comment]
Thanks, @annezazu! I'm able to reproduce on a fresh site, running a non-block-based theme. Looks like the default button styles aren't loading for some reason. I filed https://github.com/WordPress/gutenberg/issues/27773 to track it upstream, and will close this issue in the meantime.

**Comment by annezazu** [comment]
Ah! I should have thought to check a non block theme (facepalm). Thank you for handling. I've been spending too much time focusing on FSE :D
