### ISSUE TITLE
Cover Block render error when empty-theme is active

### ISSUE THREAD

**Issue by youngmicroserf** [WordPress/theme-experiments#159]
For some reason, the cover block will fail to render when the empty theme is active. Activating any other of the experimental themes solves the issue.

**Comment by carolinan** [comment]
This is related to https://github.com/WordPress/gutenberg/issues/27829
The emptytheme has support for the custom padding in the experimental-theme.json file:
```
"spacing": {
		"customPadding": true
},
```

This setting uses custom units, so a temporary fix is to add the theme support to functions.php:
```
// Add support for custom units.
add_theme_support( 'custom-units' );
```
