### ISSUE TITLE
TT1 Blocks: Do not use only capital letters for Site Title

### ISSUE THREAD

**Issue by paaljoachim** [WordPress/theme-experiments#163]
I tested out TT1 yesterday and noticed that the Site Title contained only capital letters.
This should be an option the user has, and not be forced to add CSS to adjust this aspect.

Default: SITE TITLE
Giving the option to be able to able to write: Site Title or site title
would be helpful.

Thanks.

**Comment by kjellr** [comment]
Once the Site Title block supports Text Transform, this style will be available for users to edit in the UI. [Currently](https://github.com/WordPress/gutenberg/blob/master/docs/designers-developers/developers/themes/theme-json.md#typography-properties), that setting is only available globally or for the Navigation block.

**Comment by paaljoachim** [comment]
1. I find it strange that the default is all capital letters.
2. Good to see that Text Transform will be added making it easier to adjust the letters. Hopefully it will not only be small "site title" or capital letters "SITE TITLE" but having it as "Site Title".

**Comment by kjellr** [comment]
> I find it strange that the default is all capital letters.

TT1 Blocks is just another version of Twenty Twenty-One, so we're following the design for that theme. @melchoyce, I can't recall, did the all-caps site title come up as an issue at any point before?

**Comment by melchoyce** [comment]
It didn't, as far as I recall.

**Comment by ianstewart** [comment]
I couldn't find a discrete issue for adding the letter-case controls to the site title block (just discussion on older issues) so I made a discrete issue for it.

https://github.com/WordPress/gutenberg/issues/28106

**Comment by paaljoachim** [comment]
Bringing the comment over here as well....

My initial thought on this is to start with the default casing: "Site Title"
Then text letter case can be changed to upper: "SITE TITLE" or lower "site title"

The user should be able to decide upper or lower case by using the keyboard.

**Comment by scruffian** [comment]
I added a PR for this to Gutenberg: https://github.com/WordPress/gutenberg/pull/29622
