### ISSUE TITLE
TT1 Blocks: Installation instruction step fails

### ISSUE THREAD

**Issue by evakaneva** [WordPress/theme-experiments#166]
1. Go to https://github.com/WordPress/theme-experiments/tree/master/tt1-blocks#installation
2. Follow the instructions
3. If you unzip the download, you cannot upload it.

<img width="1280" alt="Screen Shot 2021-01-11 at 19 54 07" src="https://user-images.githubusercontent.com/51059617/104232233-baa28380-5458-11eb-816f-0b7e5f6b7db6.png">

4. If I try to upload the zip (since the folder can't be uploaded) the installation fails.

<img width="1280" alt="Screen Shot 2021-01-11 at 19 54 50" src="https://user-images.githubusercontent.com/51059617/104232258-c1c99180-5458-11eb-8006-a4632192cacd.png">

Conclusion: the uploading step does not work at all, which means the folder has to be moved instead which is a lot harder for beginners.

**Comment by kjellr** [comment]
Hey @evakaneva, thanks for filing the issue! 

The way to get that uploaded correctly is to unzip the main folder (`theme-experiments`), but then create a new zip of just the individual theme's folder (`tt1-blocks`). Uploading that should allow you to install the theme as expected. 

I agree that the docs aren't clear there. Maybe something like this is better? 

---

1. In your admin panel, install and activate the Gutenberg Plugin.
2. Click the 'Code' button on the main Theme Experiments Repository GitHub page.
3. Unzip the resulting download.
4. Upload the theme to your site via one of the following methods:
A. Copy the `tt1-blocks` folder into your server's `wp-content/themes` directory.
B. Create a new zip file of the `tt1-blocks` folder. Visit Appearance > Themes, click "Add New", and then "Upload Theme" to upload this new zip file to your site. 
5. Visit Appearance > Themes and activate the "TT1 Blocks" theme.

---

Separately: We're in the process of adding TT1 Blocks to the main Theme Repository, which will simplify these steps _substantially_ for those who want to test the theme.
