### ISSUE TITLE
TT1 Blocks: Fix or remove front page template

### ISSUE THREAD

**Issue by fklein-lu** [WordPress/theme-experiments#167]
The TT1 has a `front-page.html` template that only shows the post content.

There are two main issues with this:

1. The original theme does not seem to have a front page template.
2. But front page templates need to respect the reading settings. This means that if the homepage is set to display posts, a list of posts should be displayed. So there most be a loop and a blog display here.

**Comment by carolinan** [comment]
This need to be solved with the query block(?) up streams, and the theme can be adjusted afterwards.

**Comment by fklein-lu** [comment]
No, the template needs to be fixed. Because there's no Query Block in there.

Add a Query Block to the template, have it inherit the Main Query, and it all will work as expected.

Or better yet remove the template, since the original Twenty Twenty-One theme doesn't have a front page template either, and TT1 is supposed to be a block version of that theme.
