### ISSUE TITLE
TT1 Blocks: Main element is missing

### ISSUE THREAD

**Issue by carolinan** [WordPress/theme-experiments#180]
The header template part and footer template part correctly uses `<header>` and `<footer>` elements
But in our wishes to keep the theme simple, the `<main>` element was not used to wrap the main content.

This is an oversight that has negative impacts on accessibility and it needs to be resolved.
More info: https://dequeuniversity.com/rules/axe/4.1/landmark-one-main

**Comment by carolinan** [comment]
Since the query is not a wrapping element -it has no element,
the options are to wrap the queries in a group block or use template parts.

Template parts are practical for repeated content, I suggest that the simplicity of this theme makes use of group blocks more appropriate.

**Comment by kjellr** [comment]
> I suggest that the simplicity of this theme makes use of group blocks more appropriate.

I agree, that makes sense!

**Comment by carolinan** [comment]
I thought it had been discussed and decided against already.

**Comment by kjellr** [comment]
Ah perhaps — It's totally possible that I missed it. 😄

**Comment by mtias** [comment]
> Template parts are practical for repeated content, I suggest that the simplicity of this theme makes use of group blocks more appropriate.

Agreed. We have discussed a _main_ or _content_ semantic template part, but it's a bit of overhead for something that seems simpler. Starting with group + tag seems great to me. It's always possible to convert to a template part later if needed.
