### ISSUE TITLE
TT1 Blocks: Default settings not getting applied to root in 9.9 updates to theme.json

### ISSUE THREAD

**Issue by ndiego** [WordPress/theme-experiments#200]
In the experimental-theme.json file, the default settings have been set but no root settings have been set. It makes logical sense that the root would just inherit the defaults, but this doesn't seem to be the case. So this might be a larger issue with v9.9 of Guetenberg, but I wanted to highlight it here for others testing out TT1 Blocks.

- [ ] To test, create a new post and add some paragraphs of stock text. Then set the font-size of one to Gigantic or Extra Small (these sizes do not seem to included in Core and are specifically added by this theme). 
- [ ] Confirm that the font size changes correctly in the Block Editor.
- [ ] Now look at the frontend and you will notice that the font-size has not been changed. 

The font does not appear to change because there is no `had-extra-small-font-size` specification. Now if you add the font sizes as root settings, everything works as expected. This same issue happens for color palettes, font families, etc. 

Note this is a little tricky to test because Gutenberg/WordPress includes "common" styles. So specifications like `had-large-font-size` will actually seem to work, but if you look closely, it will not actually be the size you specified in the experimental-theme.json file.

**Comment by ndiego** [comment]
I just discovered this ticket: https://github.com/WordPress/gutenberg/pull/28792/ This appears to be a larger issue with Gutenberg.

**Comment by kjellr** [comment]
I think this should be all set now. Can you confirm, @ndiego?

**Comment by ndiego** [comment]
@kjellr yup, sorry forgot to reply to this ticket after the subsequent 9.9.x releases. This is all fixed and this ticket can be closed.
