### ISSUE TITLE
TT1 Blocks: After upgrade to Gutenberg 9.9, no theme styling is appearing in the Site Editor

### ISSUE THREAD

**Issue by ndiego** [WordPress/theme-experiments#201]
After upgrading to Gutenberg version 9.9, and with version 0.4.3 of TT1 Blocks, no theme styling appears in the Site Editor. Everything works fine in the normal Block Editor and on the frontend, but for some reason the Site Editor is not receiving the settings/styles correctly from the experimental-theme.json. 

Below is what I am seeing on a fresh WP install running 5.6.1, and with no other plugin installed besides Gutenberg. 

![image](https://user-images.githubusercontent.com/4832319/107153966-4ca98900-693e-11eb-8a5a-3f170ff7b035.png)

This is related to #200 I believe. After a couple hours trying to see if it's an issue with the specifications in the theme's experimental-theme.json, I am out of luck. I tried in one of my own block-based themes and am running into the same problem.

**Comment by ndiego** [comment]
After more digging, this appears to be caused by the stylesheets not getting enqueued in the iframe in v9.9 of Gutenberg. A ticket has already been opened: https://github.com/WordPress/gutenberg/issues/28774

**Comment by troytempleman** [comment]
I'm having the same issue.

**Comment by kjellr** [comment]
The Gutenberg fix is live now, in version 9.9.1. Marking this as fixed!
