### ISSUE TITLE
TT1 Blocks: On initial install, default navigation links don't work

### ISSUE THREAD

**Issue by kjellr** [WordPress/theme-experiments#214]
The theme includes a few navigation links in the header by default: 

https://github.com/WordPress/theme-experiments/blob/62ad6fad0e65043372a1d75cb067c7f88636785b/tt1-blocks/block-template-parts/header.html#L13-L21 

Eventually, we should probably have some sort of starter content bundled with the theme that would create those pages so that the links work by default.

**Comment by annezazu** [comment]
In case it helps with determining future solutions, I wanted to share a video of how the current experience feels right now as I was testing today:

https://user-images.githubusercontent.com/26996883/108770668-d436f080-7517-11eb-943e-61f41ad58eaf.mov

You can see it gets me stuck in a pretty strange loop currently. When it comes to the FSE Outreach program, it would be great to have this be a bit more refined for future testing efforts.

**Comment by shaunandrews** [comment]
> Eventually, we should probably have some sort of starter content bundled with the theme that would create those pages so that the links work by default.

Alternatively, I think we should default to showing the placeholder state for the Navigation block; The placeholder state goes a long way towards helping people setup their menu, and the Link block can even let them create new pages.

I'm a fan of teaching people how to do this stuff, rather than trying to do it for them.

**Comment by alaczek** [comment]
> Alternatively, I think we should default to showing the placeholder state for the Navigation block

OMG YES! I love that placeholder state, it's so helpful! I reported this as an issue in Gutenberg, because _I think_ this will need some work in the editor itself: https://github.com/WordPress/gutenberg/issues/28711

**Comment by carolinan** [comment]
If we are happy with the theme preview on WordPress.org not showing a menu, then yes we can use the placeholder.

**Comment by carolinan** [comment]
And the footer social links? Is it obvious enough that they need to be updated?
