### ISSUE TITLE
TT1 Blocks: Cover block not visible in header on homepage

### ISSUE THREAD

**Issue by annezazu** [WordPress/theme-experiments#215]
While trying to figure out a way to add a cover block image to the header of a site as part of [this outreach effort](https://make.wordpress.org/test/2021/02/18/fse-program-testing-call-2-build-a-homepage-with-site-editing-blocks/#comment-1349), I found that I could add a cover block image but it wasn't visible on the site upon viewing it. Further, the navigation links are incorrect/don't match what I've changed them to. 

Here's a quick video:

https://user-images.githubusercontent.com/26996883/108780439-aa84c600-7525-11eb-823b-add697df8cd0.mov

I'm using TT1 Blocks & Gutenberg 10.1 for this.

**Comment by annezazu** [comment]
Of note, even after saving, I returned to the site editor to find these changes had been wiped out. I rebuilt the same setup and found the same error. Something odd seems to be going on.

**Comment by carolinan** [comment]
Hi,
which versions of the theme and Gutenberg was used?

**Comment by annezazu** [comment]
Version: 0.4.4!

**Comment by carolinan** [comment]
I am only able to reproduce this if I already have a template part called header saved from editing a different theme. 
I tested with several themes and it doe snot only happen with TT1 Blocks active.

If you can confirm this scenario, 
this is the issue in the Gutenberg repo: https://github.com/WordPress/gutenberg/issues/28951

**Comment by annezazu** [comment]
Oh wow!! This is fascinating. I'll close this out as I can confirm this is the case.
