### ISSUE TITLE
TT1 blocks: empty space between between header and footer

### ISSUE THREAD

**Issue by vindl** [WordPress/theme-experiments#222]
Currently we have margins around header and footer template parts in editing view of the Site Editor.

<img width="1680" alt="Screenshot 2021-02-23 at 14 36 16" src="https://user-images.githubusercontent.com/1182160/108851478-c13e2200-75e4-11eb-9c8b-8501453a258c.png">
<img width="1680" alt="Screenshot 2021-02-23 at 14 37 16" src="https://user-images.githubusercontent.com/1182160/108851483-c26f4f00-75e4-11eb-94ec-64f69e2a4ede.png">

Would it make sense to remove them so as to align the header and footer with the beginning and ending of the page respectively?

cc @kjellr

**Comment by carolinan** [comment]
The theme does not add any extra top or bottom margins around template parts.
Do you mean the editor style that Gutenberg adds?
```
.block-editor-block-list__block {
    margin-top: 28px;
    margin-bottom: 28px;
}
```
Then that is not a theme issue, but an editor issue?

**Comment by vindl** [comment]
> Then that is not a theme issue, but an editor issue?

Yep, that seems to be the case then. I'll carry this over to editor repo and close this issue. Thanks!

**Comment by creativecoder** [comment]
This can be closed, replaced by https://github.com/WordPress/gutenberg/issues/29357
