### ISSUE TITLE
TT1 Blocks: The font size of the site title cannot be changed from the default.

### ISSUE THREAD

**Issue by miminari** [WordPress/theme-experiments#227]
I did some tests following this post.
https://make.wordpress.org/test/2021/02/18/fse-program-testing-call-2-build-a-homepage-with-site-editing-blocks/

And I noticed the font size of the site title could not be changed from the default.

If you change the font size of your site from the settings, it will not change on the front view.

Editor View:
![Editor View](https://user-images.githubusercontent.com/487207/109577280-b2052a00-7b38-11eb-91f9-77ed1d7d9a7c.png)

Front View:
![Front View](https://user-images.githubusercontent.com/487207/109577884-b847d600-7b39-11eb-8349-28e497717730.png)

This is probably because no style is given to `.wp-block-site-title.has-extra-large-font-size`, and similar class names.

---

Verification environment

- TT1 Blocks Version: 0.4.4
- Gutenberg 10.0.2
- WordPress 5.6.2

- Mac OS Big Sur 11.1
- Chrome 88.0.4324.192

**Comment by carolinan** [comment]
Hi
This is related to Gutenberg and not the theme itself, it will (hopefully) be fixed with https://github.com/WordPress/gutenberg/pull/29378

**Comment by miminari** [comment]
Thank you for reply.
Does this mean that it's better not to have more styles in block based theme than can be specified in theme.json?

**Comment by aristath** [comment]
>  Does this mean that it's better not to have more styles in the block based theme than can be specified in theme.json?

It depends on the styles. Basic and "universal" styles should be in the theme.json file, while more opinionated things that make a theme stand-out and add some character would still be in CSS files.

**Comment by aristath** [comment]
I'll go ahead and close this thread since it's not related to the TT1 theme and we already have the other ticket in Gutenberg 👍
