### ISSUE TITLE
How to use: template_include

### ISSUE THREAD

**Issue by Bowriverstudio** [WordPress/theme-experiments#23]
The function: gutenberg_render_block_core_template_part

Has the line: 

$template_part_file_path =
				get_stylesheet_directory() . '/block-template-parts/' . $attributes['slug'] .'.html';

How do I get a CPT to use its own block-template-parts?  Is this the correct place to ask this?

**Comment by johnstonphilip** [comment]
@Bowriverstudio if I understand you right, you want to use something like this in your theme's html files to include template parts:

`<!-- wp:template-part {"slug":"name-of-template-part-file-without-extension","theme":"your-theme-name"} /-->`

This is how the `index.html` file in the `parisienne` theme includes its `header`:
https://github.com/WordPress/theme-experiments/blob/master/parisienne/block-templates/index.html#L2

**Comment by Bowriverstudio** [comment]
Hi John, thanks for the answer.  I've got a custom post type in a plugin and want to include a template part that is not in the child theme folder.  Does that make sense?

**Comment by johnstonphilip** [comment]
I traced the code for template-part inclusion back to here:
https://github.com/WordPress/gutenberg/blob/21304f999b1cbcc53d8ad098d297a6e9cf049e69/packages/block-library/src/template-part/index.php#L33

It doesn't look like there's any handling there for template files that would exist outside of a theme, so the only way I can see to do that would be to programmatically insert a post with the post_type set to `wp_template_part` and the slug set to match what your theme is calling as the slug. 

In this case it would be the word "header", but I guess you could call it whatever you want. For example:

```
<!-- wp:template-part {"slug":"slug-of-your-programmatically-created-template-part","theme":"your-theme-name"} /-->
```

**Comment by Bowriverstudio** [comment]
Thank you for your help John.  I think I'll just include the code I'd normally put in a plugin, in the theme for now.
