### ISSUE TITLE
Remove CSS from emptytheme?

### ISSUE THREAD

**Issue by carolinan** [WordPress/theme-experiments#231]
@kjellr Should we remove alignments-front.css from emptytheme so that it is easier to use this theme to compare the actual editor and front styles?

**Comment by youknowriad** [comment]
I think we should be able to do that after https://github.com/WordPress/gutenberg/pull/29335 lands. In fact that's exactly what I did to start working on the PR.

Removing it before the PR lands could also be an option but you might not get the alignments working properly in the frontend for posts.

**Comment by pbking** [comment]
I think seeing stock results trumps it working correctly. My 'druthers is to remove it sooner than later. I started using a different "empty theme" for that reason.

**Comment by kjellr** [comment]
I don't have a strong opinion, but I lean towards keeping it in there until https://github.com/WordPress/gutenberg/pull/29335 lands. Mostly because it's _a lot_ easier for folks to to remove that CSS than it is to re-write it if they want their theme working today.

**Comment by carolinan** [comment]
This has been done, closing-
