### ISSUE TITLE
TT1 blocks. Menu. Pages cant be added in menu

### ISSUE THREAD

**Issue by eflaten** [WordPress/theme-experiments#235]
When I select the plus to add a block in the menu, it shows no pages. Posts are there when I click the link symbol. A full list of pages works is also there, but can only be put in as a hole. How do we put pages in the menu?

**Comment by kjellr** [comment]
Thanks for the report! It looks like this may be a bug with Gutenberg, rather than the theme. I've filed a bug report here, and will close this issue in the meantime. We can always reopen this issue if it comes up again. 

https://github.com/WordPress/gutenberg/issues/29984

Thank you!
