### ISSUE TITLE
TT1 Blocks: Settings -> general 

### ISSUE THREAD

**Issue by elbsegler63** [WordPress/theme-experiments#269]
After I changed the language in "Settings" -> "General", the TT1 Block theme is no longer used. The Site Editor is removed. The site is broken.
The same thing happens if you change the "Site Title" in "Settings" -> "General".

WP 5.7.2
Theme: TT1 Blocks 0.4.7
Plugin: Gutenberg 10.7.1

![before changing](https://user-images.githubusercontent.com/85250773/120528441-c2e56600-c3db-11eb-8141-5c7f3ec7b97c.JPG)
![after changing](https://user-images.githubusercontent.com/85250773/120528484-ced12800-c3db-11eb-9b48-8979b3d571ff.JPG)

**Comment by kjellr** [comment]
Hi, @elbsegler63. Are you still experiencing this issue? I'm not seeing it in my testing. Thanks!

**Comment by elbsegler63** [comment]
Hi, Thanks for the hint.
The test is successful. The problem is fixed.
Should I do something now?

**Comment by kjellr** [comment]
We're all set then! I'll close the issue here. Thank you!
