### ISSUE TITLE
Link for gutenberg-starter-theme-blocks seems to have errors in local environment

### ISSUE THREAD

**Issue by xiazixin** [WordPress/theme-experiments#27]
I had my test environment in http://localhost/wcms_project/wordpress/ as home page. 
when I click on the home button, it went to http://localhost and not http://localhost/wcms_project/wordpress/.

**Comment by xiazixin** [comment]
didn't try the other themes, yet to see the problem persist

**Comment by kjellr** [comment]
Hey there! Thanks for testing. Yeah, this is an issue with all the themes. The navigation block can't currently include a smart link to something like `home_url()` at the moment, so these themes have to guess a URL with something like this: 

https://github.com/WordPress/theme-experiments/blob/daf71baf34a59161cee500a3dfcc20f514d9d1b4/gutenberg-starter-theme-blocks/block-template-parts/header.html#L4

Depending on your hosting config, this will either work or it won't. 😕

I've opened a Gutenberg bug so this can hopefully be built in upstream:

https://github.com/WordPress/gutenberg/issues/20542

Once that's resolved, we'll work to incorporate it in these themes. In the meantime, I'm going to close this issue so we can follow along on the new one. 

Thanks again!
