### ISSUE TITLE
correct the slug/folder name for Empty theme

### ISSUE THREAD

**Issue by carolinan** [WordPress/theme-experiments#270]
Currently the theme folder is emptytheme, the correct folder name would be `empty-theme` since the name has a space inside it.

**Comment by kjellr** [comment]
We could also change the name of the theme to Emptytheme. I've been referring to it via the single-word slug `emptytheme` in general.

**Comment by pbking** [comment]
I see that the `Text Domain: emptytheme` already.  and everything else seems to refer to 'emptytheme' already too.  Is this just a matter of changing the `Theme Name: Empty Theme` to `Theme Name: Emptytheme`?

That makes the most sense to me as it's the smaller change and my fingers already remember `emptytheme`.
