### ISSUE TITLE
Adding data-attributes to templates

### ISSUE THREAD

**Issue by dnnsjsk** [WordPress/theme-experiments#28]
Hey,

Is it possible to add data-attributes to the .html templates?

I am imagining something like that:
```html
<!-- wp:group {"align":"full","className":"site-content testest", "attributes":"[data-type="header"]"} -->
<div class="wp-block-group alignfull site-content testest" data-type="header"><div class="wp-block-group__inner-container"><!-- wp:post-title /--><!-- wp:post-content /--></div></div>
<!-- /wp:group -->
```

I know blocks are dependant on those attributes to function correctly so naturally this code results in an error, but I am still wondering if that is a possibility.

Thanks!
Dennis

**Comment by kjellr** [comment]
Hi @dnnsjsk!

Any adjustments to block markup would need to happen directly in the [github.com/wordpress/gutenberg](https://github.com/wordpress/gutenberg) repo, so you may want to suggest that there. 

Out of curiosity though, can you share an example of how a data attribute like that might come in handy? If the goal is to specify that something's a header for instance, that may be handled by something like https://github.com/WordPress/gutenberg/issues/20200

**Comment by dnnsjsk** [comment]
Hey @kjellr,

My example was a bit pointless, but data-attributes could be used to initialise various Javascript libraries.

Thanks, I will open another Issue in the Gutenberg repo.
