### ISSUE TITLE
Navigation Block Spacing Issue

### ISSUE THREAD

**Issue by annezazu** [WordPress/theme-experiments#280]
Using the latest version of GB (11.1) and latest version of TT1 on a fresh site, I am seeing differences in spacing between the editor vs front end when using the nav block:

Front end:
<img width="391" alt="Screen Shot 2021-08-09 at 2 04 39 PM" src="https://user-images.githubusercontent.com/26996883/128752843-9b2f6f4a-8dd8-433e-81a4-4c7116b50287.png">

Editor: 
<img width="392" alt="Screen Shot 2021-08-09 at 2 04 33 PM" src="https://user-images.githubusercontent.com/26996883/128752845-ce41027e-377a-4aa0-8e45-518c98e1d458.png">

I tried testing with other block themes, specifically the Q theme, and this issue wasn't present so I'm assuming this is specific to TT1.

**Comment by jasmussen** [comment]
Possibly related: https://github.com/WordPress/gutenberg/pull/33021

**Comment by annezazu** [comment]
Definitely related ^ Closing this out as it is in the columns block.
