### ISSUE TITLE
TT1 blocks: missing visuals for gradients

### ISSUE THREAD

**Issue by karmatosed** [WordPress/theme-experiments#287]
Currently using TT1, the following is what I see in Chrome on any gradient view in the full site editor:

![2021-09-20 20 48 39](https://user-images.githubusercontent.com/253067/134066256-abdd810f-db09-46b1-95a1-59d444918138.gif)

I tested with another theme, and the gradients showed, so it seems related to the theme, not the editor itself.

**Comment by carolinan** [comment]
This is because the gradients do not work with the preset CSS variables, because those variables are only in the iframe. The same problem happens in the template editor. In my opinion that should be fixed in Gutenberg.
-But until then it can be fixed in the theme.
