### ISSUE TITLE
TT1 Blocks: Visual issues

### ISSUE THREAD

**Issue by kjellr** [WordPress/theme-experiments#298]
There are a number of glaring visual issues in TT1-Blocks at the moment: 

- [ ] Content bumps up against the edges of the screen.
- [ ] The wide-aligned header, footer, and post titles are all full-width.
- [ ] The default navigation is not right-aligned.

These are likely due to old markup. We bundled up a new version in #296, but after testing the zip before merge, I'm not comfortable pushing a "new" version that looks this broken still. Let's instead fix these issues before we sync up with WordPress.org. 

## Screenshot

<img width="994" alt="Screen Shot 2021-12-17 at 7 46 09 AM" src="https://user-images.githubusercontent.com/1202812/146546753-833c5fa8-c0f6-45e5-9d50-59b1393f65e6.png">

**Comment by MaggieCabrera** [comment]
Testing #299 I've seen that index.html is loading the full content of the posts, including alignments and that looks very strange, should we show the excerpt only instead?

**Comment by kjellr** [comment]
Yeah, probably. I can add that quickly to #299
