### ISSUE TITLE
[twentytwenty blocks] Alignment Issues

### ISSUE THREAD

**Issue by jffng** [WordPress/theme-experiments#36]
**Description**
There are alignment issues in both the front-end and editor, with blocks that support wide and full width.  To recreate these issues:
 
- Activate Gutenberg 7.8.1
- Activate the TwentyTwenty Blocks theme
- Add any full or wide-width block to the page

--
In the editor:
![Kapture 2020-04-08 at 13 47 28](https://user-images.githubusercontent.com/5375500/78816506-d47dda00-799f-11ea-9967-f7693574cf27.gif)

--
_Front-end full-width image block_: The image does not take up the full width.
<img width="500" alt="Screen Shot 2020-04-08 at 12 23 40 PM" src="https://user-images.githubusercontent.com/5375500/78808841-0426e500-7994-11ea-93ad-c4bff9bfeb95.png">

--
_Front-end wide-width image block_: The image overflows to the right.
<img width="500" alt="Screen Shot 2020-04-08 at 12 23 25 PM" src="https://user-images.githubusercontent.com/5375500/78809088-61229b00-7994-11ea-8491-061eaac9fd92.png">

**Comment by carolinan** [comment]
Closing this as the theme in it's current form is not maintained.
