### ISSUE TITLE
Consider denoting or removing themes in this repo that have not been updated recently. 

### ISSUE THREAD

**Issue by kjellr** [WordPress/theme-experiments#58]
👋 As Full-Site Editing has moved forward, some of the themes in this repo no longer work nicely. This can be confusing for folks to visit this repository — it's unclear which themes are up to date and which aren't. 

I suggest we either: 

1. Test & remove themes that don't work as of Gutenberg 9.2. 
2. Update the main Readme to list each theme available in this repo, and the latest version it's been verified to work against. 

Any thoughts on those options?

**Comment by jffng** [comment]
> 1. Test & remove themes that don't work as of Gutenberg 9.2.

I just removed Parisienne and closed some out-of-date PRs. They were useful explorations but it would be good to only include working themes in the repo for now. 

> 2. Update the main Readme to list each theme available in this repo, and the latest version it's been verified to work against.

Yeah, it would be good to include a quick description for each theme and the plugin version it works with in the readme.

**Comment by jffng** [comment]
Shall we close this since we've tidied up the repo?

**Comment by kjellr** [comment]
Let's do it. Thank you!
