### ISSUE TITLE
Twenty Twenty-One Blocks: Post/Page Titles need styles

### ISSUE THREAD

**Issue by kjellr** [WordPress/theme-experiments#60]
Screenshot: 

Current: 

![Screen Shot 2020-10-22 at 3 09 04 PM](https://user-images.githubusercontent.com/1202812/96918647-9b5b1200-1478-11eb-9bdc-df91d98cbc99.png)

Original Theme: 

![Screen Shot 2020-10-22 at 3 11 31 PM](https://user-images.githubusercontent.com/1202812/96918808-e07f4400-1478-11eb-816a-3bcd4db974b8.png)

**Comment by mtias** [comment]
Let's make sure we can express the main visual aspects of these with attributes

**Comment by aristath** [comment]
Replacing `single.html` with this fixes the issue on the frontend:

```html
<!-- wp:template-part {"slug":"header","theme":"twentytwentyone-blocks","align":"full"} /-->

<!-- wp:group {"align":"wide"} -->
<div class="wp-block-group alignwide"><div class="wp-block-group__inner-container"><!-- wp:post-title {"textAlign":"left","level":1} /-->

<!-- wp:separator -->
<hr class="wp-block-separator"/>
<!-- /wp:separator --></div></div>
<!-- /wp:group -->

<!-- wp:post-content /-->

<!-- wp:post-comments /-->

<!-- wp:template-part {"slug":"footer","theme":"twentytwentyone-blocks","align":"full"} /-->
```
On the editor side there's a issue with the title's width, but front looks good 👍
