### ISSUE TITLE
Move post/page title to the top bar.

### ISSUE THREAD

**Issue by paaljoachim** [WordPress/theme-experiments#71]
**Is your feature request related to a problem? Please describe.**
In Full Site Editing there are explorations going on in relation to moving the post/page title to the top bar mid area.

It would be nice to get the post/page title to the top bar. Have the new Post/Page Title block in place. Making it possible to add a Cover Block and the Post/Page title block into it.

As the user would then finally be able to not have the page title in the content but can add it back if they choose to.

There are a few different FSE issues in relation to the above.

**Comment by kjellr** [comment]
@paaljoachim can you share a visual example of what you mean here? I'm not sure I follow.

**Comment by paaljoachim** [comment]
Hey Kjell. @kjellr 

Example. 
https://github.com/WordPress/gutenberg/issues/20877#issuecomment-698309796

In Full Site Editing the page/post name is moved to the top middle bar. We should also move the post/page title out of the Gutenberg screen and to the top middle area of the bar, and instead use the Post/Page Title block.

I took a screenshot of the gif.
![Screen Shot 2020-11-04 at 18 10 09](https://user-images.githubusercontent.com/5323259/98143172-0bca5000-1ec9-11eb-99fd-344c6ca9238f.png)

https://github.com/WordPress/gutenberg/issues/22621

**Comment by scruffian** [comment]
I moved this to the Gutenberg repo: https://github.com/WordPress/gutenberg/issues/27093
