### ISSUE TITLE
Twenty Twenty-One Blocks: Create a better fallback page for when FSE is not enabled.

### ISSUE THREAD

**Issue by carolinan** [WordPress/theme-experiments#83]
Currently, the index.php fallback page only says `// Nothing to see here.`

This can be improved by adding some additional information to logged in users about why this page is showing.

I do not know what the long term plan is for this page, but it is also possible to display a standard front page with content to logged out visitors instead of a broken, white page.

**Comment by kjellr** [comment]
Yeah, this is a global question for all FSE themes — `index.php` is required (or recommended at the very least), but it doesn't really do anything if FSE is enabled. It would be great to decide on a standard message or function for it if FSE is disabled.

**Comment by carolinan** [comment]
Part of me wants a complete working theme even when FSE is not enabled.

**Comment by aristath** [comment]
There's also the option to do something like this... https://github.com/aristath/q/blob/master/index.php
This will show a message like this to administrators:

![Screenshot_2020-11-13 Screenshot](https://user-images.githubusercontent.com/588688/99069568-4746d780-25b7-11eb-824d-15f0bbe77adb.png)

The actual text is not important and can change, but it does offer some guidance to administrators

**Comment by MaggieCabrera** [comment]
This is not relevant anymore, I was about to remove the index.php file since it's not needed anymore, but should we update the required WP version to do that? it would be the same for some other enhancements, should we make a new build of the theme with enhancements for 6.0 and ship them with that as requirement?

**Comment by carolinan** [comment]
I think we can close this issue too.
