### ISSUE TITLE
TT1 Blocks: Migrate CSS for code block

### ISSUE THREAD

**Issue by scruffian** [WordPress/theme-experiments#94]
Broken out of https://github.com/WordPress/theme-experiments/issues/82

The code is:

```
.wp-block-code {
	border-color: var(--global--color-border);
	border-radius: 0;
	border-style: solid;
	border-width: 0.1rem;
	padding: var(--global--spacing-unit);

	code {
		font-size: var(--global--font-size-xs);
		white-space: pre;
		overflow-x: auto;
		display: block;
	}
}
```

- The border settings will need to be added to Global Styles.
- IMO the white space and overflow settings can be removed to just use the ones that the block has
- display block should probably be added to the block too
- a padding control should also be added to the block

**Comment by pbking** [comment]
Padding control has been added (see linked Gutenberg PR).
Font Size and default padding have been added to theme.json

BORDER is another matter... there's a [WIP](WordPress/gutenberg#25791) that is adding border RADIUS but in the way that the rest of border will follow; That code needs to land before we can make the CODE's border customizable.
I'm unsure what the timeline for that might be so I've supplied CSS to style the border as was done in TT1.  Not sure if that will stay in.
