### ISSUE TITLE
Video Block: Migrate over default block styles as theme.json settings

### ISSUE THREAD

**Issue by scruffian** [WordPress/theme-experiments#99]
These are the video block styles:
```
.wp-block-video {

	figcaption {
		color: var(--global--color-primary);
		font-size: var(--global--font-size-xs);
		margin-top: calc(0.5 * var(--global--spacing-unit));
		margin-bottom: var(--global--spacing-unit);
		text-align: center;
	}
}
```

I don't think we need to migrate these styles as Gutenberg already has them.

```
* > figure > video {
	max-width: unset;
	width: 100%;
	vertical-align: middle;
}
```

The bottom styles are being migrated to Gutenberg: https://github.com/WordPress/gutenberg/pull/27328

Broken out of #82

**Comment by scruffian** [comment]
WordPress/gutenberg#27328 is merged so I think we can close this and mark the video block as done. @kjellr does that make sense to you?

**Comment by kjellr** [comment]
Yeah, that sounds good to me!
